
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // 注意：移除了 engine: "classic" 和 datasource.url。
  // 不指定 engine 时走 SchemaEngineConfigAbsent 分支，datasource 不再是必填项，
  // prisma generate 阶段不再强制校验 DATABASE_URL。
  // 真正的连接 URL 在 schema.prisma 里用 env("DATABASE_URL") 读取。
});
