export { GoldFishSVG } from './GoldFishSVG';
export { KoiFishSVG } from './KoiFishSVG';
export { GuppyFishSVG } from './GuppyFishSVG';
export { TropicalFishSVG } from './TropicalFishSVG';
export { TetraFishSVG } from './TetraFishSVG';
export { CoryFishSVG } from './CoryFishSVG';
export { PlecoFishSVG } from './PlecoFishSVG';
export { OtocinclusFishSVG } from './OtocinclusFishSVG';
export { AngelFishSVG } from './AngelFishSVG';
export { BettaFishSVG } from './BettaFishSVG';
export { FishAvatar } from './FishAvatar';
export type { FishVariant, FishStage } from './types';
export { FISH_VARIANTS, slugToVariant } from './types';
